### PR TITLE
 #160452444 Articles social share

### PR DESCRIPTION
**Pull request by hnobi**
#### What does this PR do?
This PR will add Article social share functionality
#### Description of Task to be completed?
- Adds FacebookShareButton  component for article social share on facebook
- Adds TwitterShareButton  component for article social share on twitter
- updates sidetool component with the insertion of facebook and twitter component

#### How should this be manually tested?

- Start the application using npm start
- Go to to [localhost:3000](http://localhost:3000)
- Login with an existing account
- On the list of articles section, click on any article of your choice
- At the right hand side of article-view click the twitter or facebook button to share the article.
- `http://localhost:3000/article/{article-slug}`

#### What are the relevant pivotal tracker stories?
#160452444
#### Screenshots (if appropriate)
screen shot 2018-11-29 at 11 03 28 am

#### Questions:

### CODE REVIEW

**Review by blackshady — APPROVED** [review]
Nice job on this PR. I have reviewed this pull request and it meet the expected story on the PT board [#160452444](https://www.pivotaltracker.com/story/show/160452444)
Looks good to me.

**Review by uchemukolo — APPROVED** [review]
This PR is good to go.  I can share on social media.

**Comment by waleCloud** [comment]
Kindly resolve the conflicts on this PR.

**Comment by waleCloud** [comment]
The build is failing. kindly fix ASAP.

**Pull request merged**
